spring:
  application:
    name: inspien
  datasource:
    url: jdbc:mysql://{HOST}:{PORT}/{DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: "DB_USERNAME"
    password: "DB_PASSWORD"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

eai:
  ftp:
    host: {FTP_HOST}
    port: 21
    username: {FTP_USERNAME}
    password: {FTP_PASSWORD}
  applicant:
    key: {APPLICANT_KEY}
    name: {진경}
    phone: "010-2440-4379"
  log:
    path: ./logs/eai-log.txt