spring:
  application:
    name: inspien
  config:
    import: optional:file:./src/main/resources/application-secret.yaml
  datasource:
    url: ${EAI_DB_URL}
    username: ${EAI_DB_USERNAME}
    password: ${EAI_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

eai:
  ftp:
    host: ${EAI_FTP_HOST}
    port: ${EAI_FTP_PORT}
    username: ${EAI_FTP_USERNAME}
    password: ${EAI_FTP_PASSWORD}
    path: ${EAI_FTP_PATH}
  applicant:
    key: ${EAI_APPLICANT_KEY}
    name: ${EAI_APPLICANT_NAME}
    phone: ${EAI_APPLICANT_PHONE}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html