spring:
  application:
    name: inspien
  config:
    import: optional:file:./src/main/resources/application-secret.yml
  datasource:
    url: ${EAI_DB_URL}
    username: ${EAI_DB_USERNAME}
    password: ${EAI_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

eai:
  ftp:
    host: ${EAI_FTP_HOST}
    port: 21
    username: ${EAI_FTP_USERNAME}
    password: ${EAI_FTP_PASSWORD}
  applicant:
    key: ${EAI_APPLICANT_KEY}
    name: 진경
    phone: ${EAI_APPLICANT_PHONE}
  log:
    path: ./logs/eai-log.txt